### ISSUE TITLE
IDCalculator UI

### ISSUE THREAD

**Issue by mkd1994** [ExternalFlux/IPC#1]
![ipcalc ui](https://cloud.githubusercontent.com/assets/11775934/7293881/536a208c-e9b1-11e4-9a03-ce780941cfff.jpg)

**Comment by m0sh1x2** [comment]
What what ? :dancers:

**Comment by mkd1994** [comment]
Imashe nujda on url adres na image ne mojeh da go kacha ot kompa direktno
